services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cart-service:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  redis_data: 