version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  user-service:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata:
